### ISSUE TITLE
Строка запроса к API

### ISSUE THREAD

**Issue by RUINArbat** [NSDDeveloper/nsddata_api#11]
1. Хотелось бы получить полный синтаксис WEB-запроса к методам API
2. Для разных приложений хочется получать свой состав и объём данных по запросу.
   На странице "Персонализация" вашего сайта даётся возможность выбора возвращаемых полей,
   в результате чего формируется параметр запроса **"exclude=**". Почти всегда запрос получается
   слишком длинный и сервер возвращает ошибку **414**.
   ## Предложения:
   - сделать параметр запроса **"include="**, который, как правило, будет короче, да и удобнее;
   - предоставить механизм: после выбора нужных полей сохранять их как именованный шаблон,
     а в запросе иметь параметр, задающий необходимый шаблон выдачи, например, **"fields="**
Спасибо, Геннадий

**Comment by vasiliy-mikhailov** [comment]
https://github.com/NSDDeveloper/nsddata_api/tree/master/CS_Advanced
