### ISSUE TITLE
Загрузка информации по однодневным облигациям через NSD API

### ISSUE THREAD

**Issue by mkivilev** [NSDDeveloper/nsddata_api#15]
Бухгалтерия грузит сделки из системы внутреннего учета в начале следующего месяца за предыдущий месяц.
При этом возникает проблема при получении информации по однодневным облигациям ВТБ,
т.к. на момент загрузки сделок, информации по ним в вашей базе уже нет.
Для примера рассмотрим облигацию ВТБКС2-208 с датой погашения 8.12.2017.
До момента открытия торгов 11.12.2017 года облигация была доступна в справочнике,
после открытия торгов информации по данной бумаге уже не стало.

Как  нам решить эту проблему, не прибегая к ежедневной загрузке данных по таким ЦБ ?

**Comment by vasiliy-mikhailov** [comment]
Технически API может предоставить информацию о снятых с обслуживания ценных бумагах, вопрос в подключенных тарифных опциях. Передал запрос своим коллегам, которые могут помочь с этим вопросом.
