### ISSUE TITLE
Реализация пагинации

### ISSUE THREAD

**Issue by mabdullaev** [NSDDeveloper/nsddata_api#20]
Добрый день! 
Подскажите, пожалуйста, у меня вопрос по поводу метода "getNews" (https://nsddata.ru/ru/products/getnews/2). 
Для реализации постраничной навигации требуется параметр о количестве новостей. 
Как лучше это сделать? Необходимо обязательно запрашивать все новости без лимита и считать количество?

**Comment by QtRoS** [comment]
Добрый день, @mabdullaev! Спасибо за ваш вопрос.
На текущий момент в сервисе нет специальной функции, позволяющей получить количество новостей. Вы можете скачивать новости последовательно небольшими порциями с помощью параметров `skip` и `limit`, используя т.н. «горячую подгрузку».
Обращаем Ваше внимание на то, что обновление новостного потока - это непрерывный процесс. 
Если у вас остались вопросы, прошу писать на Khritova.MA@nsd.ru.
