### ISSUE TITLE
Метод exists, обязательное поле, дата изменения блока данных

### ISSUE THREAD

**Issue by mrEas** [NSDDeveloper/nsddata_api#21]
Приветствую! 
1) Подскажите пожалуйста, как реализовать фильтр по исключению пустого блока атрибута "securities": [] ?

Такой запрос с моим apikey все равно возвращает данные с пустым блоком securities (limit разный ставил) - https://nsddata.ru/api/get/corpactions?limit=1000&product=2&filter={"securities":{"$exists":true}}}&apikey=DEMO
Т.е. задача получить данные ТОЛЬКО с заполненным блоком ценных бумаг (securities).

2) Что значит обязательное поле в списке атрибутов? (https://nsddata.ru/ru/products/getcorpactions/2)

3) Как мне понять, что в блоке с данными по corp_action_type были изменения? По корневым атрибутам _at и _at2? (Нужно для того, чтобы хранить историю по корпоративному действию в БД)

**Comment by MaryKhrit** [comment]
@mrEas , добрый день, 
1.  Вы можете использовать б**о**льшую детализацию, например, поле securities.id. Если оно не заполнено, то и блок пуст. 
2. Если вы имеете в виду признак "обяз." в персонализации на странице, то это значит,что поле/блок всегда присутствует в ответе. Если нет, то уточните, пожалуйста, ваш запрос.
3. Все верно, _at - дата обновления блока целиком, _at2 - дата обновления c учетом вложенных объектов.

Если у вас остались вопросы, прошу писать на <InformServices_support@nsd.ru>.

**Comment by mrEas** [comment]
Т.е. на уровне запроса из выдачи не исключить пустой блок "securities": [], который является обязательным полем? 
Тогда остается фильтровать в своем приложении. 
Спасибо!
