### ISSUE TITLE
Авторизация через MOEX

### ISSUE THREAD

**Issue by KoryakinAlexandr** [NSDDeveloper/nsddata_api#22]
В связи с переходом на новый сервис авторизации https://www.nsd.ru/ru/press/deponews/index.php?id36=634366
старая авторизация перестает работать?
И как правильно осуществлять авторизацию из кода, с# например?
Примеры API nsddata не содержат кода для авторизации.

**Comment by NSDDeveloper** [comment]
Добрый день!

Действительно, старая авторизация перестала работать через UI.
Для авторизованного доступа к API из кода необходимо указывать API-ключ в параметре `apikey` запроса, например:
`https://nsddata.ru/api/get/securities?limit=10&product=2&apikey=DEMO`
где вместо `DEMO` нужно указать Ваш API-ключ.

**Comment by KoryakinAlexandr** [comment]
спасибо, разобрался.
