### ISSUE TITLE
Возможность получения НКД на дату

### ISSUE THREAD

**Issue by ret-Phoenix** [NSDDeveloper/nsddata_api#24]
Возможно ли получить НКД на дату по ЦБ?
Предположим, сегодня 20/08/19, хочу получить НКД на 31/07/19.
Как оформить запрос используя API?

**Comment by MaryKhrit** [comment]
Добрый день!
НКД публикуется на дату T+1, то есть сегодня вы видите НКД по бумаге, рассчитанный на 22.08 + на 23.08. 
Пример ответа API на запрос по бумаге:
[
{
    "isin": "RU000A0JUG80",
    "add_info": {
        "accr_int": [
            {
                "date": "2019-08-23",
                "value": 0.023835616438356164
            },
            {
                "date": "2019-08-22",
                "value": 0.023561643835616437
            }
        ]
    }
}
]

https://nsddata.ru/api/get/securities?limit=10&product=2&filter={"isin":"RU000A0JUG80"}&include=isin,add_info.accr_int&apikey=ВАШ
