### ISSUE TITLE
Соответствие полей nsddata_api ранее действующим форматам (d1_dogovor_inf_uslugi_nekval_.pdf)

### ISSUE THREAD

**Issue by zvvvlad** [NSDDeveloper/nsddata_api#27]
Добрый день!

Разрабатываем сервис для получения данных о ценных бумагах в формате JSON. Делаем маппинг уже используемых таблиц в БД нашего банка.
 Подскажите пожалуйста. как по API получить значение для поля FUND (код ПИФ , присвоенный из НРД-файла companies) таблицы UNITS ? 

С уважением.
Владимир Зверев,
Global Consulting Group Ltd

**Comment by MaryKhrit** [comment]
Добрый день, если Вы запрашиваете через метод https://nsddata.ru/api/get/securities по конкретному паю (например, по ISIN коду), то код НРД инвестиционного фонда будет отражен в поле issuer.code_nsd. 
Через метод https://nsddata.ru/api/get/companies?filter{%22code_nsd%22:%22PIF[укажите номер]%22}&apikey=ВАШ

С уважением, 
команда Информационных сервисов

**Comment by MaryKhrit** [comment]
> Добрый день!
> 
> Разрабатываем сервис для получения данных о ценных бумагах в формате JSON. Делаем маппинг уже используемых таблиц в БД нашего банка.
> Подскажите пожалуйста. как по API получить значение для поля FUND (код ПИФ , присвоенный из НРД-файла companies) таблицы UNITS ?
> 
> С уважением.
> Владимир Зверев,
> Global Consulting Group Ltd

Добрый день, если Вы запрашиваете через метод https://nsddata.ru/api/get/securities по конкретному паю (например, по ISIN коду), то код НРД инвестиционного фонда будет отражен в поле issuer.code_nsd.
Через метод https://nsddata.ru/api/get/companies?filter{%22code_nsd%22:%22PIF[укажите номер]%22}&apikey=ВАШ

С уважением,
команда Информационных сервисов
