### ISSUE TITLE
zvvvlad@yahoo.com

### ISSUE THREAD

**Issue by zvvvlad** [NSDDeveloper/nsddata_api#28]
Добрый день!
Подскажите пожалуйста, как правильно сформировать запросы для получения всех данных отдельно по каждому инструменту:
1)share
2) unit
3) dep_receipt
4) mortgage_sertificate

Сейчас пишем условие, с целью получить только mortgage_sertificate:
https://nsddata.ru/api/get/securities?exclude=share,bond,unit,dep_receipt,clearing_certificate&limit=10&apikey=<KEY>
но получаем в ответе все виды инструментов.

**Comment by MaryKhrit** [comment]
> Добрый день!
> Подскажите пожалуйста, как правильно сформировать запросы для получения всех данных отдельно по каждому инструменту:
> 1)share
> 2) unit
> 3) dep_receipt
> 4) mortgage_sertificate
> 
> Сейчас пишем условие, с целью получить только mortgage_sertificate:
> https://nsddata.ru/api/get/securities?exclude=share,bond,unit,dep_receipt,clearing_certificate&limit=10&apikey=
> но получаем в ответе все виды инструментов.

Добрый день, используйте фильтр по "Тип финансового инструмента". Можно привязаться к наименованию, а можно к id + убрать лимит. Например, 
https://nsddata.ru/api/get/securities?filter={"instr_type.name":"акции"}&apikey=
