### ISSUE TITLE
Справочники

### ISSUE THREAD

**Issue by NSDDeveloper** [NSDDeveloper/nsddata_api#3]
Просьба предоставить  возможность скачать отдельной выгрузкой (или дополнением к текущей выгрузке) все используемые справочники.

**Comment by akatarqa** [comment]
Поддерживаю. Справочная информация должна быть доступна отдельными вызовами. Как вариант GetFieldRef(имя таблицы, имя поля) - возвращает справочник этого поля. К примеру есть в GetSecurities есть поле form (Форма выпуска), функция должна вернуть все формы выпуска. Если база реляционная, то в Securities хранить ссылка вида Form_ID с явным указанием на справочник и не составит труда его получить.

**Comment by RSa-Dev** [comment]
Согласен. Если нужно поддерживать свою базу на основе данных НРД, то без этого сложно.

**Comment by vasiliy-mikhailov** [comment]
https://nsddata.ru/en/products/getdictionaries/2
