### ISSUE TITLE
Автоматическое получение apikey

### ISSUE THREAD

**Issue by AndreyPiter** [NSDDeveloper/nsddata_api#30]
Добрый день.
Подскажите могу ли я автоматизировать со стороны пользователя получение apikey?
Задача состоит в запросе у пользователя логина/пароля и формирование get/post запроса для получения apikey. Реализован ли такой функционал?

**Comment by QtRoS** [comment]
Добрый день!
Простите за задержку в ответе. Официальной точки API для получения API-ключа по логину и паролю нет.
