### ISSUE TITLE
Недоступны тестовые данные на странице GETDICTIONARIES

### ISSUE THREAD

**Issue by zvvvlad** [NSDDeveloper/nsddata_api#31]
Добрый день!

Нужны для разработки тестовые данные со страницы 
https://nsddata.ru/ru/products/getdictionaries/2

URL https://nsddata.ru/api/get/dictionaries?limit=10&apikey=DEMO
возвращает ответ 
Not enough rights or invalid apikey

Как можно получить необходимые данные?

С уважением. 
Владимир Зверев.

**Comment by QtRoS** [comment]
@zvvvlad добрый день!
Можете воспользоваться данной выгрузкой в качестве референса.

[dictionaries.zip](https://github.com/NSDDeveloper/nsddata_api/files/4771967/dictionaries.zip)
