### ISSUE TITLE
Валидация JSON-схемой

### ISSUE THREAD

**Issue by NSDDeveloper** [NSDDeveloper/nsddata_api#4]
Просьба предоставить пример валидации

**Comment by korxal** [comment]
Например:

`string securities, schema;`
           ` using (var wc = new WebClient() { Encoding = Encoding.UTF8, })`
           ` {`
              `  securities = wc.DownloadString("https://nsddata.ru/api/get/securities?limit=10&product=2&apikey=DEMO");`
               ` schema = wc.DownloadString("https://nsddata.ru/api/schema/securities");`
         `}`
            `JSchema  JsonSchema = JSchema.Parse(schema);`
            `JArray Json = JArray.Parse(securities);`
            `if (!Json.IsValid(JsonSchema)) throw new Exception("Invalid Json!");`
