### ISSUE TITLE
Фильтры - недостаточно информации

### ISSUE THREAD

**Issue by NSDDeveloper** [NSDDeveloper/nsddata_api#5]
Хотелось бы получить формальное описание принципа построения JSON-фильтров, типовые сценарии использования, примеры и лучшие практики.

**Comment by akatarqa** [comment]
Считаю описания принципа и возможных значений более чем достаточно. 
Типовые случаи, примеры и прочее уже есть в Web форме.

**Comment by RSa-Dev** [comment]
Формальное описание: [https://github.com/clue/json-query-language/blob/master/SYNTAX.md](url)

**Comment by QtRoS** [comment]
@RSa-Dev да, действительно синтаксис запросов к API в плане фильтрации частично перекрывается с указанной Вами спецификацией. Полный перечень доступных конструкций мы в ближайшем времени сформулируем.

**Comment by vasiliy-mikhailov** [comment]
https://github.com/NSDDeveloper/nsddata_api/tree/master/CS_Advanced
