### ISSUE TITLE
getSIR и URL для выгрузки SIR-NSD через API

### ISSUE THREAD

**Issue by RSa-Dev** [NSDDeveloper/nsddata_api#6]
Сейчас URL содержит имя файла, например: .../sn?id=SIR-NSD_Standart_A_v1_0_2017_05_25_01_11_42.zip 
С учётом того, что цифры в имени файла меняются с каждым обновлением, как забирать через API-запрос - непонятно.
Предлагается отдавать файл по фиксированному URL запросу, типа  .../sn?id=SIR-NSD_Latest&apikey=... 
Более "хитрый" вариант - отдавать по фиксированному запросу URL файла, содержащий его имя. 
Тогда из имени клиент мог бы понять, обновился ли файл и надо ли в моменте его качать.

**Comment by vasiliy-mikhailov** [comment]
Перечень статичных ссылок:
SIR-NSD_Light v1.0
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Light_v1_0.zip 

База данных SIR-NSD_Light-monthly_v1.0 (для квалифицированных инвесторов)
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Light-monthly_v1_0.zip 

База данных SIR-NSD_Light-weekly_v1.0 (для квалифицированных инвесторов)
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Light-weekly_v1_0.zip 

База данных SIR-NSD_Premium-monthly_A_v1.0 (Для квалифицированных  инвесторов)
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Premium-monthly_A_v1_0.zip 

База данных SIR-NSD_Premium-weekly_A_v1.0 (Для квалифицированных  инвесторов)
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Premium-weekly_A_v1_0.zip 

База данных SIR-NSD_Premium_A_v1.0 (Для квалифицированных  инвесторов)
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Premium_A_v1_0.zip 

База данных SIR-NSD_Premium_B_v1.0 (Для неквалифицированных  инвесторов)
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Premium_B_v1_0.zip 

База данных SIR-NSD_Standart-monthly_A_v1.0 (Для квалифицированных  инвесторов)
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Standart-monthly_A_v1_0.zip 

База данных SIR-NSD_Standart-weekly_A_v1.0 (Для квалифицированных  инвесторов)
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Standart-weekly_A_v1_0.zip 

База данных SIR-NSD_Standart_A_v1.0 (Для квалифицированных  инвесторов)
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Standart_A_v1_0.zip 

База данных SIR-NSD_Standart_B_v1.0 (Для неквалифицированных  инвесторов)
https://nsddata.ru/ru/file/sn?id=SIR-NSD_Standart_B_v1_0.zip
