### ISSUE TITLE
Поиск по биржевому тикеру

### ISSUE THREAD

**Issue by Dmatafonov** [NSDDeveloper/nsddata_api#7]
Коллеги, сервис несомненно офигенный.

В раельной жизни мы правда дело с ISIN имеем опосредовано - все таки брокеры работают с биржами, ключевые данные - это тикер биржи.

Сейчас чтобы найти бумагу в НРД нужно сначала найти ее ISIN - как правило берем в данных, которые биржа присылает по шлюзу. Значит они то знают соответствие тикера и ISIN.

Было бы очень полезно и удобно если бы вы тоже знали это соответствие и по нему можно было бы вести поиск.

**Comment by korxal** [comment]
Чем такой вариант не устраивает?
api/get/securities?limit=10&product=2&**filter={"listing.code":"GAZP"}**

**Comment by Dmatafonov** [comment]
Отлично. То что нужно
