### ISSUE TITLE
Баг: невалидный json

### ISSUE THREAD

**Issue by Dmatafonov** [NSDDeveloper/nsddata_api#8]
https://nsddata.ru/api/get/securities?limit=10&product=8&filter=%7B%22isin%22:%22RU000A0JQKU8%22%7D&apikey=...

Лишняя запятая после объекта.

![image](https://user-images.githubusercontent.com/8863854/26920518-ef08cd3c-4c41-11e7-80ea-0e638e37e92a.png)

**Comment by WizARTs** [comment]
Спасибо, поправили
