### ISSUE TITLE
Часть бумаг по ISIN не находится

### ISSUE THREAD

**Issue by Dmatafonov** [NSDDeveloper/nsddata_api#9]
В основном это погашенные облигации, но по идее данные по ним у вас все равно есть. 

Посмотрите что с ними не так, для примера не найденные ISIN

RU0001011900,RU0001180440,RU0001231870,RU0001245474,RU0001245482,RU0001245631,RU0001245706,RU0001534489,RU0001534661,RU0001537839,RU0001551889,RU0001552069,RU0001552622,RU0001552630,RU0001707572,RU0001737595,RU0001987620,RU0002000373,RU0002000373,RU0002000373,RU0002000373,RU0002000373,RU0002000373,RU0002155334,RU0002260175,RU0002260183,RU0002260464,RU0002867839,RU0003691279,RU0003691287,RU0003736546,RU0003877472,RU0003877498,RU0003880096,RU0003935627,RU0003935882,RU0003935999,RU0003936146,RU0003936393,RU0003938688,RU0003939777,RU0004003102,RU0004047802,RU0005162295,RU0005229292,RU0005258770,RU0005344356,RU0005880987,RU0006325537,RU0006325545,RU0006569423,RU0006936200,RU0006941648,RU0007190963,RU0007481131,RU0007481149,RU0007483939,RU0007489621,RU0007527206,RU0007661393,RU0007661682,RU0007757472,RU0007757621,RU0007762654,RU0007764346,RU0007766127,RU0007773073,RU0007779161,RU0007779179,RU0007782421,RU0007787636,RU0007896452,RU0007896460,RU0008000443,RU0008005657,RU0008035688,RU0008035696,RU0008097886,RU0008141700,RU0008150602,RU0008151550,RU0008155908,RU0008167507,RU0008167713,RU0008168208,RU0008170238,RU0008181748,RU0008182134,RU0008182365,RU0008190152,RU0008248828,RU0008248836,RU0008253075,RU0008256904,RU0008268123,RU0008268131,RU0008268149,RU0008274204,RU0008288774,RU0008329057,RU0008415815,RU0008420278,RU0008424866,RU0008433586,RU0008434147,RU0008434238,RU0008435425,RU0008436233,RU0008436241,RU0008440193,RU0008441134,RU0008441555,RU0008442215,RU0008449111,RU0008456942,RU0008461595,RU0008465042,RU0008487418,RU0008487913,RU0008503032,RU0008508049,RU0008514567,RU0008514856,RU0008538145,RU0008548326,RU0008549761,RU0008550132,RU0008552179,RU0008569674,RU0008573555,RU0008575402,RU0008578778,RU0008582762,RU0008586870,RU0008594395,RU0008598586,RU0008605555,RU0008628417,RU0008631676,RU0008632526,RU0008632534,RU0008648993,RU0008655618,RU0008731203,RU0008776349,RU0008779996,RU0008796651,RU0008799218,RU0008799226,RU0008799234,RU0008815543,RU0008826888,RU0008826979,RU0008833827,RU0008833835,RU0008833892,RU0008909171,RU0008959630,RU0008961107,RU0008967625,RU0009003495,RU0009003503,RU0009003537,RU0009003594,RU0009003594,RU0009026678,RU0009033617,RU0009034011,RU0009034052,RU0009035265,RU0009040885,RU0009042790,RU0009043020,RU0009044242,RU0009046759,RU0009050165,RU0009060909,RU0009064364,RU0009065031,RU0009070742,RU0009071088,RU0009071393,RU0009084479,RU0009091946,RU0009099899,RU0009100085,RU0009100424,RU0009100432,RU0009101901,RU0009107684,RU0009153738,RU0009161418,RU0009167837,RU0009275234,RU0009550644,RU0009575864,RU0009700553,RU0009701239,RU0009703672,RU0009704761,RU0009705842,RU0009768915,RU0009841514,RU0009842132,RU0009842520,RU0009854046,RU0009856801,RU0009856819,RU0009858104,RU0009859599

**Comment by NSDDeveloper** [comment]
@Dmatafonov спасибо за вопрос. Данные бумаги более не находятся на обслуживании, в связи с этим они недоступны в поиске. В планах по развитию API есть планы по выгрузке таких бумаг, так что в ближайшем будущем Вы сможете подобные бумаги найти. 
Следите за новостями сервиса!
